"""Canonical domain model of the Software Development Brain.

Importing this package must never pull in provider SDKs, databases, workflow
engines, or coding agents.  The domain depends only on Pydantic.
"""

from brain.domain.actors import Actor, ActorType
from brain.domain.artifacts import Artifact, ArtifactType
from brain.domain.code_intelligence import (
    CodeRelation,
    CodeRelationType,
    ImportStatement,
    ParsedFile,
    Symbol,
    SymbolIdentity,
    SymbolKind,
    SymbolLocation,
    content_hash,
    is_test_path,
    module_from_path,
)
from brain.domain.common import Priority
from brain.domain.decisions import Decision, DecisionStatus
from brain.domain.documents import (
    Document,
    DocumentNode,
    DocumentNodeType,
    DocumentSource,
    DocumentType,
    DocumentVersion,
    SourceArtifact,
)
from brain.domain.event_types import (
    EVENT_TYPE_TO_MODEL,
    CanonicalEvent,
    DocumentChanged,
    ExecutionCompleted,
    ExecutionRequested,
    ExecutionStarted,
    FeedbackVerdict,
    HumanFeedbackReceived,
    KnowledgeConflictDetected,
    ProjectCreated,
    PullRequestCreated,
    PullRequestRequested,
    RepositoryRegistered,
    RepositoryRevisionChanged,
    RequirementChanged,
    VerificationCompleted,
    VerificationRequested,
    WorkItemAssigned,
    WorkItemChanged,
    WorkItemCreated,
    derive_event,
    event_to_model,
    model_to_envelope,
)
from brain.domain.events import EventEnvelope, EventType
from brain.domain.evidence import Evidence, EvidenceType
from brain.domain.executions import (
    Execution,
    ExecutionPermissions,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStatus,
)
from brain.domain.external_reference import ExternalReference, SourceReference
from brain.domain.identity import (
    ActorId,
    ArtifactId,
    ContextCapsuleId,
    DecisionId,
    DocumentId,
    DocumentVersionId,
    EvidenceId,
    ExecutionId,
    ProjectId,
    RepositoryChangeSetId,
    RepositoryId,
    RepositorySnapshotId,
    RequirementId,
    VerificationId,
    WorkflowId,
    WorkItemId,
)
from brain.domain.knowledge import (
    DiscoveryMethod,
    KnowledgeConfidence,
    KnowledgeEvidence,
    KnowledgeOrigin,
    RevisionScope,
    SemanticRecord,
)
from brain.domain.parsing import (
    AdrSections,
    CandidateRequirement,
    ExtractedReference,
    ParsedCodeBlock,
    ParsedDocument,
    ParsedNode,
    ParsedTable,
    ReferenceKind,
    SemanticChunk,
)
from brain.domain.projects import Project, ProjectStatus
from brain.domain.repositories import Repository
from brain.domain.repository_scan import (
    ChangedFile,
    FileCategory,
    RepositoryChangeSet,
    RepositorySnapshot,
    classify_changed_files,
    classify_file,
)
from brain.domain.requirements import (
    Constraint,
    ConstraintKind,
    Requirement,
    RequirementSource,
    RequirementSourceType,
    RequirementStatus,
)
from brain.domain.software_model import (
    ComponentType,
    Interface,
    InterfaceType,
    Resource,
    ResourceType,
    SoftwareComponent,
    SoftwareDomain,
    System,
)
from brain.domain.topology import (
    CandidateKind,
    ComponentCandidate,
    DependencyCandidate,
    DiscoveredTopology,
    InterfaceCandidate,
    ResourceCandidate,
    TopologyClaim,
    TopologyReconciler,
)
from brain.domain.verification import VerificationResult, VerificationVerdict
from brain.domain.work_items import (
    AcceptanceCriterion,
    Assignment,
    HumanWorkStatus,
    ImplementationStatus,
    PullRequestStatus,
    VerificationStatus,
    WorkItem,
    WorkItemType,
)

__all__ = [
    "AcceptanceCriterion",
    "Actor",
    "ActorId",
    "ActorType",
    "AdrSections",
    "Artifact",
    "ArtifactId",
    "ArtifactType",
    "Assignment",
    "CandidateKind",
    "CanonicalEvent",
    "CandidateRequirement",
    "ComponentCandidate",
    "ComponentType",
    "Constraint",
    "ConstraintKind",
    "ContextCapsuleId",
    "ChangedFile",
    "classify_changed_files",
    "classify_file",
    "CodeRelation",
    "CodeRelationType",
    "content_hash",
    "Decision",
    "DecisionId",
    "DecisionStatus",
    "DependencyCandidate",
    "derive_event",
    "DiscoveredTopology",
    "DiscoveryMethod",
    "Document",
    "DocumentChanged",
    "DocumentId",
    "DocumentNode",
    "DocumentNodeType",
    "DocumentSource",
    "DocumentType",
    "DocumentVersion",
    "DocumentVersionId",
    "EventEnvelope",
    "EVENT_TYPE_TO_MODEL",
    "EventType",
    "Evidence",
    "EvidenceId",
    "EvidenceType",
    "event_to_model",
    "Execution",
    "ExecutionCompleted",
    "ExecutionId",
    "ExecutionPermissions",
    "ExecutionRequest",
    "ExecutionRequested",
    "ExecutionResult",
    "ExecutionStarted",
    "ExecutionStatus",
    "ExternalReference",
    "ExtractedReference",
    "FeedbackVerdict",
    "FileCategory",
    "HumanFeedbackReceived",
    "HumanWorkStatus",
    "ImplementationStatus",
    "ImportStatement",
    "Interface",
    "InterfaceCandidate",
    "InterfaceType",
    "is_test_path",
    "KnowledgeConflictDetected",
    "KnowledgeConfidence",
    "KnowledgeEvidence",
    "KnowledgeOrigin",
    "model_to_envelope",
    "module_from_path",
    "ParsedCodeBlock",
    "ParsedDocument",
    "ParsedFile",
    "ParsedNode",
    "ParsedTable",
    "Priority",
    "Project",
    "ProjectCreated",
    "ProjectId",
    "ProjectStatus",
    "PullRequestCreated",
    "PullRequestRequested",
    "PullRequestStatus",
    "ReferenceKind",
    "Repository",
    "RepositoryChangeSet",
    "RepositoryChangeSetId",
    "RepositoryId",
    "RepositoryRegistered",
    "RepositoryRevisionChanged",
    "RepositorySnapshot",
    "RepositorySnapshotId",
    "Requirement",
    "RequirementChanged",
    "RequirementId",
    "RequirementSource",
    "RequirementSourceType",
    "RequirementStatus",
    "Resource",
    "ResourceCandidate",
    "ResourceType",
    "RevisionScope",
    "SemanticChunk",
    "SemanticRecord",
    "SoftwareComponent",
    "SoftwareDomain",
    "SourceArtifact",
    "SourceReference",
    "Symbol",
    "SymbolIdentity",
    "SymbolKind",
    "SymbolLocation",
    "System",
    "TopologyClaim",
    "TopologyReconciler",
    "VerificationCompleted",
    "VerificationId",
    "VerificationRequested",
    "VerificationResult",
    "VerificationStatus",
    "VerificationVerdict",
    "WorkItem",
    "WorkItemAssigned",
    "WorkItemChanged",
    "WorkItemCreated",
    "WorkItemId",
    "WorkItemType",
    "WorkflowId",
]
