"""Strong, typed internal identifiers.

Internal IDs are always generated by the brain and are independent of any
external provider (Jira, OpenProject, GitLab, ...).  Each entity kind gets a
distinct NewType so that callers cannot accidentally pass a ``WorkItemId``
where a ``ProjectId`` is expected, while remaining plain ``uuid.UUID`` values
at runtime so they serialize cleanly through Pydantic and map directly to
PostgreSQL UUID columns.
"""

from __future__ import annotations

import uuid
from typing import NewType

ProjectId = NewType("ProjectId", uuid.UUID)
RepositoryId = NewType("RepositoryId", uuid.UUID)
WorkItemId = NewType("WorkItemId", uuid.UUID)
RequirementId = NewType("RequirementId", uuid.UUID)
DocumentId = NewType("DocumentId", uuid.UUID)
DocumentVersionId = NewType("DocumentVersionId", uuid.UUID)
ActorId = NewType("ActorId", uuid.UUID)
ExecutionId = NewType("ExecutionId", uuid.UUID)
ArtifactId = NewType("ArtifactId", uuid.UUID)
EvidenceId = NewType("EvidenceId", uuid.UUID)
DecisionId = NewType("DecisionId", uuid.UUID)
VerificationId = NewType("VerificationId", uuid.UUID)
ContextCapsuleId = NewType("ContextCapsuleId", uuid.UUID)
WorkflowId = NewType("WorkflowId", uuid.UUID)
RepositorySnapshotId = NewType("RepositorySnapshotId", uuid.UUID)
RepositoryChangeSetId = NewType("RepositoryChangeSetId", uuid.UUID)


def new_project_id() -> ProjectId:
    return ProjectId(uuid.uuid4())


def new_repository_id() -> RepositoryId:
    return RepositoryId(uuid.uuid4())


def new_work_item_id() -> WorkItemId:
    return WorkItemId(uuid.uuid4())


def new_requirement_id() -> RequirementId:
    return RequirementId(uuid.uuid4())


def new_document_id() -> DocumentId:
    return DocumentId(uuid.uuid4())


def new_document_version_id() -> DocumentVersionId:
    return DocumentVersionId(uuid.uuid4())


def new_actor_id() -> ActorId:
    return ActorId(uuid.uuid4())


def new_execution_id() -> ExecutionId:
    return ExecutionId(uuid.uuid4())


def new_artifact_id() -> ArtifactId:
    return ArtifactId(uuid.uuid4())


def new_evidence_id() -> EvidenceId:
    return EvidenceId(uuid.uuid4())


def new_decision_id() -> DecisionId:
    return DecisionId(uuid.uuid4())


def new_verification_id() -> VerificationId:
    return VerificationId(uuid.uuid4())


def new_context_capsule_id() -> ContextCapsuleId:
    return ContextCapsuleId(uuid.uuid4())


def new_workflow_id() -> WorkflowId:
    return WorkflowId(uuid.uuid4())


def new_repository_snapshot_id() -> RepositorySnapshotId:
    return RepositorySnapshotId(uuid.uuid4())


def new_repository_change_set_id() -> RepositoryChangeSetId:
    return RepositoryChangeSetId(uuid.uuid4())
