"""State repository ports.

Canonical transactional state.  In-memory implementations exist for tests;
PostgreSQL implementations in Phase 2 must satisfy the same contract tests.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from brain.domain.actors import Actor
from brain.domain.artifacts import Artifact
from brain.domain.decisions import Decision
from brain.domain.documents import (
    Document,
    DocumentNode,
    DocumentVersion,
)
from brain.domain.evidence import Evidence
from brain.domain.executions import Execution
from brain.domain.identity import (
    ActorId,
    ArtifactId,
    DecisionId,
    DocumentId,
    DocumentVersionId,
    EvidenceId,
    ExecutionId,
    ProjectId,
    RepositoryId,
    RequirementId,
    VerificationId,
    WorkItemId,
)
from brain.domain.projects import Project
from brain.domain.repositories import Repository
from brain.domain.requirements import Requirement
from brain.domain.verification import VerificationResult
from brain.domain.work_items import WorkItem


@runtime_checkable
class ProjectRepository(Protocol):
    async def create(self, project: Project) -> Project: ...

    async def get(self, project_id: ProjectId) -> Project | None: ...

    async def list(self) -> list[Project]: ...

    async def update(self, project: Project) -> Project: ...

    async def delete(self, project_id: ProjectId) -> None: ...


@runtime_checkable
class RepositoryRepository(Protocol):
    async def create(self, repository: Repository) -> Repository: ...

    async def get(self, repository_id: RepositoryId) -> Repository | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Repository]: ...

    async def update(self, repository: Repository) -> Repository: ...

    async def delete(self, repository_id: RepositoryId) -> None: ...


@runtime_checkable
class ActorRepository(Protocol):
    async def create(self, actor: Actor) -> Actor: ...

    async def get(self, actor_id: ActorId) -> Actor | None: ...

    async def list(self) -> list[Actor]: ...

    async def update(self, actor: Actor) -> Actor: ...

    async def delete(self, actor_id: ActorId) -> None: ...


@runtime_checkable
class WorkItemRepository(Protocol):
    async def create(self, work_item: WorkItem) -> WorkItem: ...

    async def get(self, work_item_id: WorkItemId) -> WorkItem | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[WorkItem]: ...

    async def list_by_work_item(self, parent_id: WorkItemId) -> list[WorkItem]: ...

    async def update(self, work_item: WorkItem) -> WorkItem: ...

    async def delete(self, work_item_id: WorkItemId) -> None: ...


@runtime_checkable
class RequirementRepository(Protocol):
    async def create(self, requirement: Requirement) -> Requirement: ...

    async def get(self, requirement_id: RequirementId) -> Requirement | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Requirement]: ...

    async def list_by_parent(self, parent_id: RequirementId) -> list[Requirement]: ...

    async def update(self, requirement: Requirement) -> Requirement: ...

    async def delete(self, requirement_id: RequirementId) -> None: ...


@runtime_checkable
class DocumentRepository(Protocol):
    async def create(self, document: Document) -> Document: ...

    async def get(self, document_id: DocumentId) -> Document | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Document]: ...

    async def find_by_source(self, project_id: ProjectId, source_uri: str) -> Document | None: ...

    async def update(self, document: Document) -> Document: ...

    async def delete(self, document_id: DocumentId) -> None: ...

    async def add_version(self, version: DocumentVersion) -> DocumentVersion: ...

    async def get_version(self, version_id: DocumentVersionId) -> DocumentVersion | None: ...

    async def list_versions(self, document_id: DocumentId) -> list[DocumentVersion]: ...

    async def add_node(self, node: DocumentNode) -> DocumentNode: ...

    async def list_nodes(self, version_id: DocumentVersionId) -> list[DocumentNode]: ...


@runtime_checkable
class ExecutionRepository(Protocol):
    async def create(self, execution: Execution) -> Execution: ...

    async def get(self, execution_id: ExecutionId) -> Execution | None: ...

    async def list_by_work_item(self, work_item_id: WorkItemId) -> list[Execution]: ...

    async def update(self, execution: Execution) -> Execution: ...


@runtime_checkable
class DecisionRepository(Protocol):
    async def create(self, decision: Decision) -> Decision: ...

    async def get(self, decision_id: DecisionId) -> Decision | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Decision]: ...

    async def update(self, decision: Decision) -> Decision: ...

    async def delete(self, decision_id: DecisionId) -> None: ...


@runtime_checkable
class EvidenceRepository(Protocol):
    async def create(self, evidence: Evidence) -> Evidence: ...

    async def get(self, evidence_id: EvidenceId) -> Evidence | None: ...

    async def list_by_execution(self, execution_id: ExecutionId) -> list[Evidence]: ...


@runtime_checkable
class ArtifactRepository(Protocol):
    async def create(self, artifact: Artifact) -> Artifact: ...

    async def get(self, artifact_id: ArtifactId) -> Artifact | None: ...

    async def list_by_project(self, project_id: ProjectId) -> list[Artifact]: ...


@runtime_checkable
class VerificationResultRepository(Protocol):
    async def create(self, result: VerificationResult) -> VerificationResult: ...

    async def get(self, verification_id: VerificationId) -> VerificationResult | None: ...

    async def list_by_execution(self, execution_id: ExecutionId) -> list[VerificationResult]: ...
