"""context engine: context capsules

Revision ID: 0b22b6909405
Revises: ec215a98e751
Create Date: 2026-08-15 15:56:14.384988

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b22b6909405'
down_revision: Union[str, None] = 'ec215a98e751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_capsules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('revision', sa.String(length=255), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allocations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('model_budget_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capsule_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_capsules_created', 'context_capsules', ['created_at'], unique=False)
    op.create_index('ix_context_capsules_work_item', 'context_capsules', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_capsules_work_item', table_name='context_capsules')
    op.drop_index('ix_context_capsules_created', table_name='context_capsules')
    op.drop_table('context_capsules')
    # ### end Alembic commands ###