"""command failures

Revision ID: 17bf87828832
Revises: ac90d71ee4fd
Create Date: 2026-08-27 16:20:19.708356

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bf87828832'
down_revision: Union[str, None] = 'ac90d71ee4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('command_type', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('retry_eligible', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_command_failures_command', 'command_failures', ['command_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_command_failures_command', table_name='command_failures')
    op.drop_table('command_failures')
    # ### end Alembic commands ###