"""policies: approvals

Revision ID: 6db282a31f29
Revises: 818860b00a6c
Create Date: 2026-08-17 09:51:20.677127

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db282a31f29'
down_revision: Union[str, None] = '818860b00a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.String(length=30), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_work_item', 'approvals', ['work_item_id'], unique=False)
    op.create_index('ix_approvals_workflow', 'approvals', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_workflow', table_name='approvals')
    op.drop_index('ix_approvals_work_item', table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###