"""workflow: checkpoints

Revision ID: 818860b00a6c
Revises: b10b3eacaf2a
Create Date: 2026-08-16 19:06:41.227208

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '818860b00a6c'
down_revision: Union[str, None] = 'b10b3eacaf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_index('ix_workflow_checkpoints_workflow', 'workflow_checkpoints', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_checkpoints_workflow', table_name='workflow_checkpoints')
    op.drop_table('workflow_checkpoints')
    # ### end Alembic commands ###