"""observability metrics

Revision ID: 9b8c25293dc3
Revises: 6db282a31f29
Create Date: 2026-08-17 10:12:29.429594

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b8c25293dc3'
down_revision: Union[str, None] = '6db282a31f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_capsule_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('context_token_count', sa.BigInteger(), nullable=False),
    sa.Column('candidate_count', sa.BigInteger(), nullable=False),
    sa.Column('selected_entity_count', sa.BigInteger(), nullable=False),
    sa.Column('retrieval_source_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jit_retrieval_requests', sa.BigInteger(), nullable=False),
    sa.Column('selected_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_capsule_id')
    )
    op.create_index('ix_context_metrics_execution', 'context_metrics', ['execution_id'], unique=False)
    op.create_table('context_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('missing_files_discovered_later', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verifier_omitted_dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_context_requests', sa.BigInteger(), nullable=False),
    sa.Column('irrelevant_context_rate', sa.Float(), nullable=False),
    sa.Column('retry_caused_by_context_failure', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_table('execution_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('tool_calls', sa.BigInteger(), nullable=False),
    sa.Column('commands_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retries', sa.BigInteger(), nullable=False),
    sa.Column('verification_outcome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('ix_execution_metrics_workflow', 'execution_metrics', ['workflow_id'], unique=False)
    op.create_table('impact_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('predicted_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_metrics')
    op.drop_index('ix_execution_metrics_workflow', table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_table('context_outcomes')
    op.drop_index('ix_context_metrics_execution', table_name='context_metrics')
    op.drop_table('context_metrics')
    # ### end Alembic commands ###