"""initial schema

Revision ID: a3df7db15659
Revises: 
Create Date: 2026-08-15 10:12:36.313788

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3df7db15659'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_project_id', 'artifacts', ['project_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consequences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_project_id', 'decisions', ['project_id'], unique=False)
    op.create_table('document_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('heading_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('child_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_item_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_nodes_version_id', 'document_nodes', ['version_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_versions_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_execution_id', 'evidence', ['execution_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('executor_id', sa.UUID(), nullable=False),
    sa.Column('context_capsule_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_execution_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_work_item_id', 'executions', ['work_item_id'], unique=False)
    op.create_table('external_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('external_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'provider', 'external_id', name='uq_external_references_owner_provider_external')
    )
    op.create_index('ix_external_references_owner', 'external_references', ['owner_type', 'owner_id'], unique=False)
    op.create_index('ix_external_references_provider_external', 'external_references', ['provider', 'external_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('repositories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clone_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('current_revision', sa.String(length=255), nullable=True),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repositories_project_id', 'repositories', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('derived_from', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_parent_id', 'requirements', ['parent_id'], unique=False)
    op.create_index('ix_requirements_project_id', 'requirements', ['project_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('requirement_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('architecture_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('static_analysis_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_results_execution_id', 'verification_results', ['execution_id'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('assignee', sa.UUID(), nullable=True),
    sa.Column('assignment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_work_status', sa.String(length=50), nullable=False),
    sa.Column('implementation_status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('pull_request_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_items_parent_id', 'work_items', ['parent_id'], unique=False)
    op.create_index('ix_work_items_project_id', 'work_items', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_items_project_id', table_name='work_items')
    op.drop_index('ix_work_items_parent_id', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index('ix_verification_results_execution_id', table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index('ix_requirements_project_id', table_name='requirements')
    op.drop_index('ix_requirements_parent_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_repositories_project_id', table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('projects')
    op.drop_index('ix_external_references_provider_external', table_name='external_references')
    op.drop_index('ix_external_references_owner', table_name='external_references')
    op.drop_table('external_references')
    op.drop_index('ix_executions_work_item_id', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_evidence_execution_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_document_versions_document_id', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_nodes_version_id', table_name='document_nodes')
    op.drop_table('document_nodes')
    op.drop_index('ix_decisions_project_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_artifacts_project_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('actors')
    # ### end Alembic commands ###