"""optimization quality and feedback

Revision ID: ac90d71ee4fd
Revises: e8456a6fc328
Create Date: 2026-08-17 12:54:08.877744

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac90d71ee4fd'
down_revision: Union[str, None] = 'e8456a6fc328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.Column('previous_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adjusted_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_feedback_work_item', 'context_feedback', ['work_item_id'], unique=False)
    op.create_table('executor_quality',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('executor_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('successes', sa.BigInteger(), nullable=False),
    sa.Column('failures', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_retries', sa.BigInteger(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executor_id', 'task_type', name='uq_executor_quality')
    )
    op.create_index('ix_executor_quality_task_type', 'executor_quality', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executor_quality_task_type', table_name='executor_quality')
    op.drop_table('executor_quality')
    op.drop_index('ix_context_feedback_work_item', table_name='context_feedback')
    op.drop_table('context_feedback')
    # ### end Alembic commands ###