"""document nodes: unresolved references

Revision ID: b017be05d7e2
Revises: c4412667a8cd
Create Date: 2026-08-15 11:09:11.169261

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b017be05d7e2'
down_revision: Union[str, None] = 'c4412667a8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_nodes',
        sa.Column('unresolved_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_nodes', 'unresolved_refs')
    # ### end Alembic commands ###