"""work management: mappings and conflicts

Revision ID: b10b3eacaf2a
Revises: b104417e2ae3
Create Date: 2026-08-15 16:57:36.440142

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10b3eacaf2a'
down_revision: Union[str, None] = 'b104417e2ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('provider_field', sa.String(length=100), nullable=False),
    sa.Column('provider_value', sa.String(length=500), nullable=False),
    sa.Column('brain_value', sa.String(length=500), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_conflicts_work_item', 'sync_conflicts', ['work_item_id'], unique=False)
    op.create_table('work_management_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('sync_state', sa.String(length=30), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'provider', name='uq_work_management_mapping')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_management_mappings')
    op.drop_index('ix_sync_conflicts_work_item', table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    # ### end Alembic commands ###