"""event foundation: idempotency keys and event log

Revision ID: b437f17a0f30
Revises: a3df7db15659
Create Date: 2026-08-15 10:34:03.444196

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b437f17a0f30'
down_revision: Union[str, None] = 'a3df7db15659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_event_log_correlation_id', 'event_log', ['correlation_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    op.drop_index('ix_event_log_correlation_id', table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###