"""repository scanning: snapshots and change sets

Revision ID: c4412667a8cd
Revises: b437f17a0f30
Create Date: 2026-08-15 10:49:39.432527

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4412667a8cd'
down_revision: Union[str, None] = 'b437f17a0f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_change_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('old_revision', sa.String(length=255), nullable=True),
    sa.Column('new_revision', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repository_change_sets_repository_id', 'repository_change_sets', ['repository_id'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tree', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dockerfiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compose_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ci_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documentation_roots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_roots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'revision', name='uq_repository_snapshots_repo_revision')
    )
    op.create_index('ix_repository_snapshots_repository_id', 'repository_snapshots', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_snapshots_repository_id', table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index('ix_repository_change_sets_repository_id', table_name='repository_change_sets')
    op.drop_table('repository_change_sets')
    # ### end Alembic commands ###