"""observations journal

Revision ID: c92d21acc327
Revises: 17bf87828832
Create Date: 2026-08-27 20:55:04.181851

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c92d21acc327'
down_revision: Union[str, None] = '17bf87828832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('repository_revision', sa.String(length=255), nullable=True),
    sa.Column('context_capsule_id', sa.UUID(), nullable=True),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_human_attention', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_dedup', 'observations', ['dedup_key'], unique=False)
    op.create_index('ix_observations_project', 'observations', ['project_id'], unique=False)
    op.create_index('ix_observations_work_item', 'observations', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_work_item', table_name='observations')
    op.drop_index('ix_observations_project', table_name='observations')
    op.drop_index('ix_observations_dedup', table_name='observations')
    op.drop_table('observations')
    # ### end Alembic commands ###