"""software topology: catalog tables and claims

Revision ID: e13c40194aed
Revises: b017be05d7e2
Create Date: 2026-08-15 11:43:30.911767

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e13c40194aed'
down_revision: Union[str, None] = 'b017be05d7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('schema_ref', sa.Text(), nullable=True),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interfaces_component_id', 'interfaces', ['component_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_project_id', 'resources', ['project_id'], unique=False)
    op.create_table('software_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('repository_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner', sa.UUID(), nullable=True),
    sa.Column('lifecycle', sa.String(length=100), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_software_components_project_id', 'software_components', ['project_id'], unique=False)
    op.create_table('software_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_software_domains_project_id', 'software_domains', ['project_id'], unique=False)
    op.create_table('systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('component_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_systems_project_id', 'systems', ['project_id'], unique=False)
    op.create_table('topology_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_kind', sa.String(length=30), nullable=False),
    sa.Column('entity_name', sa.String(length=500), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topology_claims_entity', 'topology_claims', ['entity_kind', 'entity_name'], unique=False)
    op.create_index('ix_topology_claims_repository_id', 'topology_claims', ['repository_id'], unique=False)
    op.create_table('topology_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topology_dependencies_project', 'topology_dependencies', ['project_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topology_dependencies_project', table_name='topology_dependencies')
    op.drop_table('topology_dependencies')
    op.drop_index('ix_topology_claims_repository_id', table_name='topology_claims')
    op.drop_index('ix_topology_claims_entity', table_name='topology_claims')
    op.drop_table('topology_claims')
    op.drop_index('ix_systems_project_id', table_name='systems')
    op.drop_table('systems')
    op.drop_index('ix_software_domains_project_id', table_name='software_domains')
    op.drop_table('software_domains')
    op.drop_index('ix_software_components_project_id', table_name='software_components')
    op.drop_table('software_components')
    op.drop_index('ix_resources_project_id', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_interfaces_component_id', table_name='interfaces')
    op.drop_table('interfaces')
    # ### end Alembic commands ###