"""runtime observations

Revision ID: e8456a6fc328
Revises: 9b8c25293dc3
Create Date: 2026-08-17 12:31:26.903174

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8456a6fc328'
down_revision: Union[str, None] = '9b8c25293dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('revision', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runtime_observations_execution', 'runtime_observations', ['execution_id'], unique=False)
    op.create_index('ix_runtime_observations_revision', 'runtime_observations', ['repository_id', 'revision'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runtime_observations_revision', table_name='runtime_observations')
    op.drop_index('ix_runtime_observations_execution', table_name='runtime_observations')
    op.drop_table('runtime_observations')
    # ### end Alembic commands ###