"""execution workspace isolation

Adds base branch / working branch / worktree path columns to executions so
every execution records its isolated workspace (Phase 37, Task 37.5).

Revision ID: e9f2b9b2a1c0
Revises: c92d21acc327
Create Date: 2026-08-29 10:45:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e9f2b9b2a1c0'
down_revision: Union[str, None] = 'c92d21acc327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('base_branch', sa.String(length=200), nullable=True))
    op.add_column('executions', sa.Column('working_branch', sa.String(length=200), nullable=True))
    op.add_column('executions', sa.Column('worktree_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'worktree_path')
    op.drop_column('executions', 'working_branch')
    op.drop_column('executions', 'base_branch')
    # ### end Alembic commands ###