"""code intelligence: symbols, relations and files

Revision ID: ec215a98e751
Revises: e13c40194aed
Create Date: 2026-08-15 13:23:49.291007

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec215a98e751'
down_revision: Union[str, None] = 'e13c40194aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('module', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'revision', 'path', name='uq_code_files_repo_rev_path')
    )
    op.create_table('code_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('source_identity_key', sa.String(length=1500), nullable=False),
    sa.Column('target_identity_key', sa.String(length=1500), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('target_path', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_relations_repo_revision', 'code_relations', ['repository_id', 'revision'], unique=False)
    op.create_index('ix_code_relations_source', 'code_relations', ['source_identity_key'], unique=False)
    op.create_index('ix_code_relations_target', 'code_relations', ['target_identity_key'], unique=False)
    op.create_table('code_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=500), nullable=False),
    sa.Column('qualified_name', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('identity_key', sa.String(length=1500), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('return_annotation', sa.Text(), nullable=True),
    sa.Column('decorators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('symbol_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_symbols_identity_key', 'code_symbols', ['identity_key'], unique=False)
    op.create_index('ix_code_symbols_qualified', 'code_symbols', ['repository_id', 'qualified_name'], unique=False)
    op.create_index('ix_code_symbols_repo_revision', 'code_symbols', ['repository_id', 'revision'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_symbols_repo_revision', table_name='code_symbols')
    op.drop_index('ix_code_symbols_qualified', table_name='code_symbols')
    op.drop_index('ix_code_symbols_identity_key', table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_index('ix_code_relations_target', table_name='code_relations')
    op.drop_index('ix_code_relations_source', table_name='code_relations')
    op.drop_index('ix_code_relations_repo_revision', table_name='code_relations')
    op.drop_table('code_relations')
    op.drop_table('code_files')
    # ### end Alembic commands ###