"""audit trail

Adds the audit_events table recording who/what triggered a command, which
executor ran, what revision/changes/verdict were involved, and which external
tools were updated (Phase 40, Task 40.7).

Revision ID: f3a1c2d4e5f6
Revises: e9f2b9b2a1c0
Create Date: 2026-08-29 12:30:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3a1c2d4e5f6'
down_revision: Union[str, None] = 'e9f2b9b2a1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###